#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataAccessModel;

namespace DataAccessModel	
{
	public partial class Product
	{
		private int _idProducts;
		public virtual int IdProducts
		{
			get
			{
				return this._idProducts;
			}
			set
			{
				this._idProducts = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private decimal? _price;
		public virtual decimal? Price
		{
			get
			{
				return this._price;
			}
			set
			{
				this._price = value;
			}
		}
		
		private string _text;
		public virtual string Text
		{
			get
			{
				return this._text;
			}
			set
			{
				this._text = value;
			}
		}
		
		private IList<Transaction> _transactions = new List<Transaction>();
		public virtual IList<Transaction> Transactions
		{
			get
			{
				return this._transactions;
			}
		}
		
	}
}
#pragma warning restore 1591
