#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using DataAccessModel;

namespace DataAccessModel	
{
	public partial class Transaction
	{
		private int _idTransaction;
		public virtual int IdTransaction
		{
			get
			{
				return this._idTransaction;
			}
			set
			{
				this._idTransaction = value;
			}
		}
		
		private int _idCustomer;
		public virtual int IdCustomer
		{
			get
			{
				return this._idCustomer;
			}
			set
			{
				this._idCustomer = value;
			}
		}
		
		private int _idProduct;
		public virtual int IdProduct
		{
			get
			{
				return this._idProduct;
			}
			set
			{
				this._idProduct = value;
			}
		}
		
		private decimal? _amount;
		public virtual decimal? Amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				this._amount = value;
			}
		}
		
		private string _customerName;
		public virtual string CustomerName
		{
			get
			{
				return this._customerName;
			}
			set
			{
				this._customerName = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private Customer _customer;
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
		}
		
		private Product _product;
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
		}
		
	}
}
#pragma warning restore 1591
